### ISSUE TITLE
testing/globals of themeTurnPlot

### ISSUE THREAD

**Issue by bvreede** [elpaco-escience/talkr#104]
We have a theme for convenience, but it is 1. untested, and 2. throws a few warnings because functions are used that are 'undefined globals'. I suspect this is because packages aren't declared/imported, and we do not get actual errors because there are no tests (see 1.).

This should probably be addressed before CRAN submission.

**Comment by bvreede** [comment]
pinging @PabRod — maybe this can be fixed by using `ggthemes::` calls in the themeTurnPlot?

**Comment by PabRod** [comment]
I think so.

Also, consider using `@importFrom` in the docstring. Maybe not the best for consistency within this project, but definitely not a bad practice.
