### ISSUE TITLE
create hex logo for `talkr`

### ISSUE THREAD

**Issue by mdingemanse** [elpaco-escience/talkr#108]
indeed @bvreede we need a hex logo, I'm happy to try my hand at this

**Comment by mdingemanse** [comment]
quick first mockup

![image](https://github.com/user-attachments/assets/6f10529d-acb0-45ce-b63c-b1c0c96db602)

**Comment by mdingemanse** [comment]
Slight tweakers. I think I prefer the left one

![image](https://github.com/user-attachments/assets/fa741592-8af2-4c03-98fe-03e5b89d8345)

**Comment by bvreede** [comment]
+1 on the left one; also, _really_ nice :)

**Comment by mdingemanse** [comment]
see https://github.com/elpaco-escience/talkr/compare/main...108-logo in 108-logo branch

for dimensions I am relying on http://hexb.in/sticker.html and for location I am relying on https://usethis.r-lib.org/reference/use_logo.html but perhaps there are other considerations (e.g. is it possible/useful to also include a pdf or svg version?)

**Comment by mdingemanse** [comment]
btw the below mockup is less refined but thinking ahead, if we add support for waveforms and spectrograms in a future version, sth like this might be a direction to take it in (taking advantage of the cubistic nature of a hexagon)

![image](https://github.com/user-attachments/assets/8b186436-fb3d-47b9-9bde-8d27566c8a3b)

**Comment by PabRod** [comment]
I like the 2D, more minimalistic one better.

**Comment by mdingemanse** [comment]
Me too! I got into my habit of generating an obviously worse variant just to make the good one stick — affliction of my past life as a freelance graphic designer with picky clients 😄
