### ISSUE TITLE
Improve `plot_quality()` labeling

### ISSUE THREAD

**Issue by mdingemanse** [elpaco-escience/talkr#116]
Currently `plot_quality()` generates a three panel plot only one of which has a `label`, due to [this line](https://github.com/elpaco-escience/talkr/blob/main/R/plots.R#L47): 

```
    labels = c("", "", source),
```

But `workflows.Rmd` refers to these as A, B, and C. Better to use those as labels, so make it:

```
    labels = c("A", "B","C"),
```

And if we do need the source name, use a `ggtitle()` in panel C.

**Comment by mdingemanse** [comment]
Making this change (commit: https://github.com/elpaco-escience/talkr/compare/main...116-plot_quality) results in a better plot in the vignette:

![image](https://github.com/user-attachments/assets/acb88fe3-903f-468b-9c29-40840b2a4959)

**Comment by PabRod** [comment]
Fixed by updating snapshot (https://github.com/elpaco-escience/talkr/commit/93b6ae471682747ce87480da3743ef95838d03b7)
