### ISSUE TITLE
Tests seem to be running as intended, but I do get a Permission denied error

### ISSUE THREAD

**Issue by mdingemanse** [elpaco-escience/talkr#118]
Possibly an issue unique to my configuration, but I'm finding that when I update the package locally, build it, and run tests, the tests do run but they also produce a Permission denied error:

```
Warning (test-plot_quality.R:26:3): plot is saved and writes message
cannot remove file 'Rplots.pdf', reason 'Permission denied'
Backtrace:
    ▆
 1. └─base::file.remove("Rplots.pdf") at test-plot_quality.R:26:3
 ```

Probably related, I find that the test tries to write a PDF and png plot to the `tests/testthat/` folder, which subsequently turn up in my git tab, but which I don't think I should be comitting:
![image](https://github.com/user-attachments/assets/15ef0a3c-8c01-4ab3-bb69-0301f752a427)

**Comment by PabRod** [comment]
Let's take a look at this next time we are in the same room.

**Comment by PabRod** [comment]
Split into #123 and #124.
