### ISSUE TITLE
consider publishing `ifadv` on CRAN too

### ISSUE THREAD

**Issue by mdingemanse** [elpaco-escience/talkr#120]
TL;DR: `Remotes` are not allowed in CRAN.

Consider publishing `ifadv` package on CRAN too. Would that make sense?

_Originally posted by @PabRod in https://github.com/elpaco-escience/talkr/issues/117#issuecomment-2312288338_

**Comment by mdingemanse** [comment]
I am not opposed. It is a very tiny, simple package which does only one thing, namely provide a (so far) text-only version of IFADV as processed by `scikit-talk`. Here's what CRAN says:

> CRAN hosts packages of publication quality and is not a development platform. A package’s contribution has to be non-trivial. 

I guess the non-trivial part is debatable. However, there are precedents for data packages, e.g., `igraph` https://cran.rstudio.com/web/packages/igraphdata/ though the level of documentation and utility of that one is not something that ifadv will approach.

I don't love the extra work (and redundant work) it likely requires; was quite happy with the soft release on github, also because as academics we're not necessarily looking forward to maintaining a whole slew of packages.

(Let's not forget that we're only running into this because of superficial clash between the original IFADV license and the licensing requirements of escience center. If that were not an issue, we would have redistributed a portion of IFADV data with `talkr` for demonstration purposes, etc., which was the original idea.)

**Comment by PabRod** [comment]
Under these circumstances, I suggest refactoring the way we access `ifadv` into a simple download. It's uglier, but it will solve the problem in a satisfying way both for CRAN and for us. If you agree, I can do it.

**Comment by mdingemanse** [comment]
Agreed!

**Comment by PabRod** [comment]
Let's close this option, at least for now.

I'm working on a fix on #117.
