### ISSUE TITLE
add `geom_turn()` functionality

### ISSUE THREAD

**Issue by mdingemanse** [elpaco-escience/talkr#14]
A turn is a time-bound unit produced by a participant in conversation. It has minimally a `begin`, `end` and `participant` (who produced it). Often it will also have have `utterance` (what is being said).

Often it has additional features like `nwords` (how many words it contains), `freq` (corpus frequency of this utterance), `rank` (corpus rank of this format), `type` (talk, laughter, breath, or some other conduct specified in the corpus).

Based on its direct environment it further comes with additional measures like `priorby` (whether the prior turn was produced by self or other), `overlapped` (whether it is overlapped by some other turn), `overlap` (whether it overlaps some prior turn), `FTO` (timing relative to prior turn by other).

Based on its immediate temporal past it may come with more measures like `talk_rel` (how much talk was produced by this participant in the prior 10s window), `transitions` (how many speaker changes there were in the prior 10s), etc.

At base, `geom_turn()` should excel in the time-aligned display of series of turns as conversation unfolds. It should have a bounding box of some kind (e.g. `geom_rect()`) and something like a `label` aesthetic onto which we could map what is said (like the `label` argument of `geom_text()`).

Many of the additional features should be mappable as aesthetics to the height, fill, colour, alpha, linewidth etc. of the bounding box. 

The alpha version of convplot does this in a rudimentary way using a combination of `geom_rect()` and `geom_text()`. The goal of `geom_turn()` should be to combine these with sensible defaults and room for customisation, in true ggplot spirit.

**Comment by mdingemanse** [comment]
Possibly relevant for text fitting magic: https://cran.r-project.org/web/packages/ggfittext/vignettes/introduction-to-ggfittext.html

**Comment by bvreede** [comment]
A potential call could look like this:

```
data |>
   ggplot2::ggplot( ... ) +
   talkr::geom_turn(aes(begin = "begin_time", end = "end_time", participants = "speaker")) # or without quotes?
```

**Comment by n400peanuts** [comment]
Here's the [code](https://ideophone.org/snailplot-rmd/) provided by Mark on his blog

**Comment by n400peanuts** [comment]
I am unpacking a bit the situation, by studying the [code](https://ideophone.org/snailplot-rmd/) to reproduce exactly the figures (both the one in the polar coordinates and in the "rect" mode) in addition to have a geom_turn() we also need a theme_*() and probably also a stats() methods.  

The commit 3c35f07031736c15fbdbf238578ea6fe3ba86f03 solves the `theme` part by having a `talkr::theme_turnPlot()` which incorporates ggthemes::theme_tufte + all the ad-hoc ggplot2::theme() personalisation. Both by visual inspection and my unit tests confirm that the using the talkr::theme_turnPlot() produces the same figure.  

Will work now on the stats/geom part now.

**Comment by mdingemanse** [comment]
Amazing! BTW I would note that the polar coordinates one really is a playful example, not necessarily a sensible default to implement in the package. Ultimately ideally it would be as simple as adding `coord_polar()` to a vanilla conversation plot.

One question I have about the theme part (being a novice myself) is whether hardcoding those ad hoc personalizations makes it harder for others to do their own customization if they wanted to use `geom_turn()` but with different theme settings. Basically, if we stripped everything theme_tufte() related (which is just my own preference for clean plots), the goal would be that `geom_turn()` still looks reasonable and has sensible defaults. 

One question is how to deal with participant labels. There are two issues with this.

1. In the old convplot, these are done by converting participants to integers (`participant_int`) then treating these as y coordinates (1, 2, etc.). Participants are then given A, B `axis.text.y` labels using `LETTERS` (a bit hacky). Works okay for when you only want to plot one line (and multiple samples), but is harder if you want to plot a whole conversation (= multiple lines of same participant). However, I can imagine that people would expect the actual participant names to show up on the y axis, in which case this needs another mapping.
2. In the case where we want to plot not one-liner samples but a whole conversation, the y coordinates are set by combining `line` and `participant_int` (so that participant B, which is participant_int 2, ends up at y coordinate line+2). This may need rethinking, because now (e.g. in the `plot_conversation()` type plot in #18)  we're putting not the participant labels but the line numbers on the y-axis. The question is, what then is a good way to display the participant labels or names?

Sorry for verbosity but at this stage of making basic design choices it's important to hammer out the details in the most optimal way possible!

**Comment by mdingemanse** [comment]
A working example of issue 1 can be gotten by running the old convplot code with the new IFADV data. My old convplot function (and @bvreede 's first implementation of it in convplot-now-talkr) does this trick with the labels as can be seen at line 117 in the code here: https://github.com/elpaco-escience/talkr/blob/main/R/convplot.R#L117 

However (and confusingly, I admit) the code in the walkthrough on my blog doesn't do this, and this is why question 2 above comes up, and why when doing that blog I started realising the two plot types are really different use cases, as described in #18. This all notwithstanding, the goal for geom_turn() is precisely to have a geom that generalizes across these two different types of plots.

Makes sense to leave some of this for when there's a minimum viable version of `geom_turn()`, then we can actually point to what we're talking about :D

**Comment by mdingemanse** [comment]
Perhaps it is useful to spell out in a bit more detail what `geom_turn()` would improve over the clunky way this is done in the old convplot. The key (and ugly) part in the old code is in two parts:

1. At [line 106](https://github.com/elpaco-escience/talkr/blob/main/R/convplot.R#L106), a wild guess is made at how long a geom_rect is going to be and based on that `utterance` is truncated to `uttshort`: 

```
      dplyr::mutate(striplength = case_when(duration < 300 ~ 3,
                                     duration >= 300 ~ round(duration/90)),
             uttshort = ifelse(nchar <= striplength | nchar <= 4,
                               utterance,
                               paste0(stringx::strtrim(utterance,striplength),'~'))) |>
```

2. Then later we add a `geom_rect()`, and if content=T, a `geom_text()` whose label is the `uttshort` we created above.
[Line 119](https://github.com/elpaco-escience/talkr/blob/main/R/convplot.R#L119):
```
     geom_rect(aes(xmin=begin0,xmax=end0,ymin=participant_int-0.4,ymax=participant_int+0.4),
                #linewidth=1,
                fill="grey90",color="white")
```
and [line 131](https://github.com/elpaco-escience/talkr/blob/main/R/convplot.R#L131) 
```
      p <- p + geom_text(aes(label=uttshort,x=begin0+60),
                         color="black",hjust=0,size=3)
```

This works okay-ish for a plot like this:

```
these_uids <- ifadv |> filter(utterance == "ja?") |> select(uid) |> unlist() |> as.character()
convplot(data=ifadv,uids=these_uids,content=T,highlight=T,window=10000)
```

![image](https://user-images.githubusercontent.com/9883915/230084835-8954619d-95c4-456e-8b5d-9b9617d27cc0.png)

However, there are multiple downsides:
- For setting the height and the y coordinates of the bounding box, we're hardcoding some values into the call to `geom_rect()`. It would be much better to allow these to be set via aesthetics relative to some sensible default.
- For setting the colour (outline) and fill we're again hardcoding values in the `geom_rect()` call, but obviously these too should be settable through aesthetics.
- For combining `geom_rect()` and `geom_text()`, we're just guessing how much space we have based on `duration`; but actually the available space depends on plotting resolution and plot size, which ggplot can handle quite nicely. We're not using ggplot strenghts here.
- We're truncating text, which is far from ideal if the point is to make visible what is being said
- We're truncating even if we _do_ have enough space, as can be seen in the example above. 
- We're layering a `geom_text()` over a `geom_rect()` and the two don't know about each other. 

A true `geom_turn()` would improve upon these issues: 
- It would allow mapping colour, fill, height, alpha to particular aesthetics (instead of hardcoding them)
- It would implement the y-placement of participants and lines in way that would make it play will with the to-be-added `geom_wave() that would plot the waveform
- For combining bounding box and text, it would try to find the best fit of utterance content relative to bounding box. To make things not look too crazy it would probably do this over the entire plot (i.e. don't size individual turns to their boxes, but pick a font size that works best for the whole thing)
- Text bounded by a box should not overflow that box by default (= it should be cropped)
- Perhaps in some orientations, text wrapping would make sense (e.g. when you have enough height to show multiple lines in a bounding box  
- Plot elements would resize depending on the plot size or plot resolution, bringing cropped content in view at larger resolutions and rewrapping when sensible.

**Comment by mdingemanse** [comment]
Thanks for the very useful call Eva! I look forward to more work on this.

FYI, just for future reference here are two visual examples of why ultimately we want the height of geom_turn rectangles to be also available as an aesthetic (instead of being hardcoded in the geom_rect call as it is in legacy convplot). 

Sometimes it looks aesthetically quite nice to have the turns overlap a bit, as in this figure from our ACL paper (this is a relative height of 0.6 above and below the y centerline):
![image](https://user-images.githubusercontent.com/9883915/231118601-053205df-d9e4-46c4-a551-897aa0cfd3a4.png)

Sometimes you might even want to map some other statistic to height. In the example below, the higher (and more overlapping) the rectangles are, the more competitive the speech in that fragment is. We do this by adjusting the height of the box by some multiple of `load` (a measure of the degree of competitiveness in a 10 second window, already available in talkr-formatted data).
![image](https://user-images.githubusercontent.com/9883915/231117098-b461e6d6-794e-47ec-a1cf-04ff034b8491.png)

I'm dropping these here just for future reference, I understand the implementation will first have to focus on the basics.
