### ISSUE TITLE
turn visualizations into geoms

### ISSUE THREAD

**Issue by bvreede** [elpaco-escience/talkr#22]
We want our conversation visualization to be geometries that can be included in a ggplot.

Some useful material:
- [a tutorial on making a geom](https://www.youtube.com/watch?v=ZMHJdW6a20I) from Rladies Melbourne
- A [gallery full of inspiration](https://exts.ggplot2.tidyverse.org/gallery/) with other ggplot-compatible libraries

See also #14

**Comment by n400peanuts** [comment]
@n400peanuts
