### ISSUE TITLE
add to geom_turn() the text functionality

### ISSUE THREAD

**Issue by n400peanuts** [elpaco-escience/talkr#26]
FYI @bvreede, just met with @mdingemanse this morning and we defined this new issue.

### Goal of this issue
Improve upon `geom_turn()` to integrate rectangles + text (rather than points), and to colour highlighted parts of the speech. 

### Output to replicate
<img src="https://user-images.githubusercontent.com/24624390/231117935-3aa3edd4-b53a-45db-baba-9034bc648409.png" width="50%" height="50%" > 

### MRE to reproduce the plot above

```
devtools::install_github("elpaco-escience/ifadv")
devtools::install_github("elpaco-escience/talkr") # note this points to main

these_uids <- ifadv::ifadv |> dplyr::filter(utterance == "ja?") |> dplyr::select(uid) |> unlist() |> as.character()
talkr::convplot(data = ifadv::ifadv, uids = these_uids[1 : 6], content = TRUE, highlight = TRUE, window = 10000)
```

### `geom_turn` will accept the following arguments:

```
#' @data input dataframe 
#' @uids vector of strings that is used to subset the data -- used if you don't have any UIDs but it takes the data itself 
#' @n_uid integer, number of rows, if uids is NULL - this is used as highlighting argument in the plot
#' @window integers referring to ms scale -- used to filter the data
#' @before integers referring to ms scale -- used to filter the data
#' @after integers referring to ms scale -- used to filter the data

```

I expect to close thi issues by next friday. I will update this estimate further if necessary.

cheers

**Comment by n400peanuts** [comment]
Note that this issue will also try to cover Mark's https://github.com/elpaco-escience/talkr/issues/14#issuecomment-1502999820

**Comment by mdingemanse** [comment]
Happened to stumble upon Danielle Navarro's description of the `grid` package that underlies ggplot (she is coauthoring a new ggplot book with Wickham), and I was pleased to see that ggplot is indeed able by design to have elements with properties that depend on other properties (as here we want text to resize based on available space in a rect): https://blog.djnavarro.net/posts/2023-03-31_generative-art-with-grid/

Perhaps too abstract to be useful but just sharing in case you're interested

**Comment by n400peanuts** [comment]
omg @mdingemanse this is **SO** useful. I found very little material about how grid works, and how it works in relation to ggplot2. The only available material so far it's their previous version of the ggplot2 book which unfortunately doesn't cover everything for development.

**Comment by bvreede** [comment]
See #47 for the continuation of this question.
