### ISSUE TITLE
Brainstorming names for the R package

### ISSUE THREAD

**Issue by bvreede** [elpaco-escience/talkr#5]
@mdingemanse wrote:

I've been brainstorming names. `convoplot()` may be useful as the name of one of the convenience functions we supply but we need something more generic and preferably something that links us to scikit-talk.

I think our best option is **TalkR** (appears not to exist yet). Some others I considered are TalkPlot, TurnVis, DiscourseR, InteractR, but they all seem more overwrought. TalkR is nice and short, uses the common 'r at end' nomenclature, and links to scikit-talk through the common keyword. It can also, of course, be read as 'talker'.

(It would be fun if that also worked as an acronym. A close enough hit is _Tools for Analyzing Language {K, R}_. Perhaps Tools for Analyzing Language in its Key Residence. Or unorthodox spellings like Konversation / Kommunication. If we have kinematic data at some point it could be Tools for Analyzing Language and Kinesics in R :D. But anyway, acronym is nice to have, not a need to have.)

**Comment by bvreede** [comment]
I like talkR! Do we want it to have a capital T or lowercase?

Perhaps too late — but I asked chatGPT for some ideas as well:

CHART: "Conversation History Analysis and Reporting Tools." 

VISTA: "Visualizing Information and Speech Through Analysis." 

TALKMAP: "Tools for Analyzing Language and Knowledge Mapping in Plots."

DISCERN: "Dialogue Information and Storyline Conversation Evaluation and Reporting Tools."

**Comment by bvreede** [comment]
I really do like talkR, also because of the shared name with scikit-talk. And in terms of explaining algorithm: "Tools for Analyzing Language in its Key Residence" works really well imho!

**Comment by mdingemanse** [comment]
On browsing the list of package names [here](https://cran.r-project.org/web/packages/available_packages_by_name.html) I think the general convention for R packages today is to not start with a capital. On the status of the final letter I'm less clear — tidyverse parlance seems to also have it in lowercase (e.g. `dplyr`, `magrittr`, `bardr`), which would mean `talkr`; but there also seem to be just as many packages with a final R that do capitalize it (`klustR`, `labstatR`, `liveChatR`) which would argue for `talkR`.

Based just on aesthetic whims I feel like keeping it lowercase — **`talkr`**.
