### ISSUE TITLE
CRAN submission

### ISSUE THREAD

**Issue by bvreede** [elpaco-escience/talkr#61]
Checklist ([source](https://cran.r-project.org/web/packages/submission_checklist.html)):

Edit (by @PabRod): the checklist is outdated, no need to use it now.

**Comment by PabRod** [comment]
# Relevant check results

## Warnings
- [ ] Checking for unstated dependencies in examples
```r 
❯ checking for unstated dependencies in examples ... OK
   WARNING
  ‘qpdf’ is needed for checks on size reduction of PDFs
  ```
  ### `--as-cran` only
  - [ ] Checking PDF version of manual
  ```r
  * checking PDF version of manual ... WARNING
LaTeX errors when creating PDF version.
This typically indicates Rd problems.
LaTeX errors found:
! LaTeX Error: File `inconsolata.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

! Emergency stop.
<read *> 
         
l.326 ^^M
         
!  ==> Fatal error occurred, no output PDF file produced!
  ```
  ## Notes
  - [ ] Checking R code for possible problems
  
 ```r
 ❯ checking R code for possible problems ... NOTE
  add_lines: no visible global function definition for ‘end’
  add_lines: no visible binding for global variable ‘begin’
  add_lines: no visible binding for global variable ‘line’
  add_lines: no visible binding for global variable ‘end’
  convplot: no visible binding for global variable ‘begin’
  convplot: no visible binding for global variable ‘uid’
  convplot: no visible binding for global variable ‘scope’
  convplot: no visible binding for global variable ‘participant’
  convplot: no visible binding for global variable ‘end’
  convplot: no visible binding for global variable ‘participation’
  convplot: no visible global function definition for ‘case_when’
  convplot: no visible binding for global variable ‘striplength’
  convplot: no visible binding for global variable ‘utterance’
  convplot: no visible binding for global variable ‘participant_int’
  convplot: no visible global function definition for ‘theme_tufte’
  convplot: no visible binding for global variable ‘begin0’
  convplot: no visible binding for global variable ‘end0’
  convplot: no visible global function definition for ‘filter’
  convplot: no visible binding for global variable ‘focus’
  convplot: no visible binding for global variable ‘uttshort’
  generate_plots: no visible binding for global variable ‘lang’
  get_uid_metadata: no visible binding for global variable ‘begin’
  get_uid_metadata: no visible binding for global variable ‘distance’
  get_uids: no visible binding for global variable ‘language’
  plot_FTO: no visible binding for global variable ‘FTO’
  plot_FTO: no visible binding for global variable ‘duration’
  plot_conversation: no visible binding for global variable ‘striplength’
  plot_conversation: no visible binding for global variable ‘utterance’
  plot_conversation: no visible binding for global variable
    ‘participant_int’
  plot_conversation: no visible binding for global variable ‘begin0’
  plot_conversation: no visible binding for global variable ‘end0’
  plot_conversation: no visible binding for global variable ‘uttshort’
  plot_token_rank: no visible binding for global variable ‘n’
  plot_token_rank: no visible binding for global variable ‘word’
  plot_top_turn_types: no visible binding for global variable ‘n’
  plot_top_turn_types: no visible binding for global variable
    ‘utterance_stripped’
  plot_transitions: no visible binding for global variable ‘FTO’
  plot_turn_duration: no visible binding for global variable ‘duration’
  prepare_convplot: no visible binding for global variable ‘language’
  process_for_plot: no visible binding for global variable ‘n’
  Undefined global functions or variables:
    FTO begin begin0 case_when distance duration end end0 filter focus
    lang language line n participant participant_int participation scope
    striplength theme_tufte uid utterance utterance_stripped uttshort
    word
  Consider adding
    importFrom("stats", "end", "filter", "line")
  to your NAMESPACE file.
  ```
  
  ### `--as-cran` only
  - [ ] Checking HTML version of manual  
  ```r
❯ checking HTML version of manual ... NOTE
Skipping checking HTML validation: no command 'tidy' found
  ```
  - [ ] Checking for non-standard things in the check directory
  ```r
❯ checking for non-standard things in the check directory ... NOTE
Found the following files/directories:
  ‘talkr-manual.tex’
  ```

**Comment by bvreede** [comment]
Tagging @pablo! Are you able to tackle these?

Most of it, as far as I can see, hinges on ifadv installation (btw: does
this need to be called twice in the description file? Once via Remotes,
once separately?). Not sure what the fix is, so I hope Pablo has an idea?

Thanks!!

**Comment by PabRod** [comment]
The `ifadv` package seems to be the main offender, indeed. One question for @mdingemanse: do they give you the option to answer these emails?

**Comment by PabRod** [comment]
Splitted into issue #117

**Comment by mdingemanse** [comment]
> The `ifadv` package seems to be the main offender, indeed. One question for @mdingemanse: do they give you the option to answer these emails?

I've forwarded the email to you.

**Comment by mdingemanse** [comment]
Is there a way for us to check whether with the recent changes it is now passing the test? Would love to get some human eyes to look at it for CRAN!

**Comment by PabRod** [comment]
I'd say we are ready for a new submission. Do you want me to do it, or prefer to try it yourself? It is quite straightforward and takes no more than 10 minutes.

**Comment by mdingemanse** [comment]
I'd be happy if you can do this round @PabRod but once we're in the same place perhaps you can show me how it works.

**Comment by PabRod** [comment]
Dear @mdingemanse, you'd like to know that I just resubmitted.

Just so you know, the steps are:

0. Go to RStudio's `Build` menu
1. Make sure `Check` passes
2. Build the package, it will generate a `*.<version>.tar.gz` file
3. Go to [CRAN's submission page](https://cran.r-project.org/submit.html) and fill in the blanks. And rejoice that most of them are auto-filled from `DESCRIPTION`

**Comment by mdingemanse** [comment]
Okay. The confirmation link asks me to confirm that I've run winbuilder so I'm trying to do that using [this form](https://win-builder.r-project.org/upload.aspx).

However before I do so, the Check on my system runs into the issue I reported before, of one of the test plots not wanting to be removed.

```
✔  checking for unstated dependencies in 'tests' ... 
─  checking tests ...
─  Running 'testthat.R' (7.1s)
E  Some test files failed
   Running the tests in 'tests/testthat.R' failed.
   Last 13 lines of output:
     cannot remove file 'plot_quality.png', reason 'Permission denied'
     Backtrace:
         ▆
      1. └─base::file.remove(path)
      
```

**Comment by PabRod** [comment]
Dear @mdingemanse,

I just uploaded the tarball Winbuilder check. You are listed as the only maintainer so the results will be mailed to you later today.

Regarding your tests, let's take a look at that in person.

**Comment by mdingemanse** [comment]
Excellent. No errors, just two notes. These are the relevant log lines:
``` 
Found the following (possibly) invalid URLs:
  URL: git@github.com:elpaco-escience/talkr
    From: README.md
    Message: Invalid URI scheme
  URL: https://codecov.io/github/elpaco-escience/talkr (moved to https://app.codecov.io/github/elpaco-escience/talkr)
    From: README.md
    Status: 301
    Message: Moved Permanently
  URL: https://fon.hum.uva.nl/IFA-SpokenLanguageCorpora/IFADVcorpus/
    From: inst/doc/workflows.html
    Status: Error
    Message: schannel: SNI or certificate check failed: SEC_E_WRONG_PRINCIPAL (0x80090322) - Der Zielprinzipalname ist falsch.
  For content that is 'Moved Permanently', please change http to https,
  add trailing slashes, or replace the old by the new URL.
* checking R code for possible problems ... NOTE
add_lines: no visible binding for global variable '.data'
add_lines: no visible global function definition for ':='
plot_density: no visible binding for global variable '.data'
plot_scatter: no visible binding for global variable '.data'
report: no visible binding for global variable '.data'
report_combined: no visible binding for global variable '.data'
tokenize: no visible binding for global variable '.data'
Undefined global functions or variables:
  .data :=
...
* DONE
Status: 2 NOTEs
```

**Comment by mdingemanse** [comment]
Re the URLs, I don't think we can fix the IFADV one (their certificate is not valid anymore).
Should we fix the Codecov one?

Re the "no visible binding for global variable", I am not sure how to interpret it but since it is a note and not an error I guess it is low priority.

**Comment by mdingemanse** [comment]
I see that the fon.uva.nl site does have a valid certificate, it's just that they have tied it to the www subdomain. So this URL is valid, and we should use it: https://www.fon.hum.uva.nl/IFA-SpokenLanguageCorpora/IFADVcorpus/

**Comment by mdingemanse** [comment]
So, PR for that URL https://github.com/elpaco-escience/talkr/pull/122

**Comment by mdingemanse** [comment]
I lost track of this — did we resubmit? Should we be expecting a response?

**Comment by PabRod** [comment]
We did resubmit, indeed. As the main author, all the communications should arrive in your inbox (not very practical, I know).

**Comment by PabRod** [comment]
Just submitted `v0.1.2`.

@mdingemanse, as the maintainer, you should have received a confirmation email that requires your acceptance. Please share any updates! :)

**Comment by PabRod** [comment]
Dear @mdingemanse, can you please provide me one or two key references for addressing the second point[^1]? 

[^1]: "Add references to DESCRIPTION"

**Comment by PabRod** [comment]
[From text to talk](http://doi.org/10.18653/v1/2022.acl-long.385) looks like the key reference. Am I right, @mdingemanse?

**Comment by mdingemanse** [comment]
Just to record here, too, that the package has cleared all hurdles and is on its way to CRAN now! Finally time to celebrate @bvreede and @PabRod !

One thing that I don't think we know yet is how this may or may not affect regular work. It is probably useful to have a development branch on github in which we can keep iterating. 

- What do we need to know about releases, versions, etc.? 
- What is the minimum kind of change that justifies a version bump and a resubmission to CRAN? 
- Would CRAN be pulling directly from a git branch or do we have to go through the manual submission route anytime we want to release a new version?

**Comment by mdingemanse** [comment]
Hmm, I just pushed a [simple update](https://github.com/elpaco-escience/talkr/commit/ccec0fa75919049b7aad832569289f3b2ae7c55a) to readme and it looks like R CMD check chokes on this. I have no idea where to begin to investigate what's wrong...

https://github.com/elpaco-escience/talkr/actions/runs/12317973358
