### ISSUE TITLE
Remove unnecessary dependencies: cowplot

### ISSUE THREAD

**Issue by bvreede** [elpaco-escience/talkr#64]

**Comment by mdingemanse** [comment]
For combining plots, `cowplot` is one of three main ways to do so (ggplot doesn't offer this out of the box). Here's a description of the three: https://r-charts.com/ggplot2/combining-plots/

If we want to keep combining plots in `plot_quality()`, we need to pick the most dependable of these and use it as a (suggest?) dependency. Any thoughts @bvreede @PabRod ?

**Comment by PabRod** [comment]
Our options regarding `cowplot` (or equivalent):

```mermaid
graph TD
Provide[Provide function combining plots] --> Yes{Yes} --> Import
Provide --> No{No} --> Vignette[Mention it in vignette] --> Mention{Just mention} --> Nothing[Do nothing]
Vignette --> Use{Run in example} --> Suggests
```

**Comment by bvreede** [comment]
I'm OK with keeping it. It has an express purpose; this issue was opened because we wanted to clean up possible unnecessary dependencies, and this one is a necessary one ¯\_(ツ)_/¯
